### PR TITLE
Makes Auth routes pathless

### PR DESCRIPTION
**Pull request by benjaminsehl**
A small tweak to the app starters to change auth routes to make them pathless so that `/auth/login` becomes `/login`.

### CODE REVIEW

**Comment by dan-gamble** [comment]
Would it make sense to add the option to have this configurable?

**Review by jplhomer — APPROVED** [review]
✨ beautiful!

**Comment by jplhomer** [comment]
> Would it make sense to add the option to have this configurable?

@dan-gamble since this is just in the template, you could configure it however you want 👍

**Comment by dan-gamble** [comment]
Derp 🤦‍♂️

**Pull request merged**
